#!/usr/bin/php -q
<?php

// Set up our variables to be usable by PHP
$opts = array();
$argv0 = array_shift($argv);

while(count($argv)) {
    $key = array_shift($argv);
    $value = array_shift($argv);
    $opts[$key] = $value;
}


include('/usr/share/microweber-hosting-scripts/cpanel/install.php');
exit();

 