#!/usr/bin/php -q
<?php

// Set up our variables to be usable by PHP

if(isset($_SERVER['argv']) and !empty($_SERVER['argv'])){
    $argv = $_SERVER['argv'];
}


$opts = array();
$argv0 = array_shift($argv);

while(count($argv)) {
    $key = array_shift($argv);
    $value = array_shift($argv);
    $opts[$key] = $value;
}


require('/usr/share/microweber-hosting-scripts/cpanel/install.php');


$msg = print_r($opts, true);
//mail("boksiora@gmail.com", "debug", $msg);

exit();

