#!/usr/bin/php -q
<?php

// Set up our variables to be usable by PHP

if(isset($_SERVER['argv']) and !empty($_SERVER['argv'])){
    $argv = $_SERVER['argv'];
}

$opts = array();
$argv0 = array_shift($argv);

while(count($argv)) {
    $key = array_shift($argv);
    $value = array_shift($argv);
    $opts[$key] = $value;
}


// Choose one of the following

// to make actual install
// require('/usr/share/microweber-hosting-scripts/cpanel/shared_install.php');

// only prepare the install and let the user do it

 require('/usr/share/microweber-hosting-scripts/cpanel/prepare_shared_install.php');



exit();
